/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Laboratorio-Info
 */
public class CalculadoraIMC_GUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraIMC_GUI
     */
    public CalculadoraIMC_GUI() {
        initComponents();
        img1_img.setVisible(false);
        img2_img.setVisible(false);
        img3_img.setVisible(false);
        img4_img.setVisible(false);
        img5_img.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        FECHAR_BTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        peso_txt = new javax.swing.JTextField();
        alt_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LIMPAR_BTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        resp_txt = new javax.swing.JLabel();
        Enviar_BTN = new javax.swing.JButton();
        img1_img = new javax.swing.JLabel();
        img2_img = new javax.swing.JLabel();
        img3_img = new javax.swing.JLabel();
        img4_img = new javax.swing.JLabel();
        img5_img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Calculadora de IMC"));
        jPanel2.setLayout(null);

        FECHAR_BTN.setForeground(new java.awt.Color(204, 0, 0));
        FECHAR_BTN.setText("X");
        FECHAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FECHAR_BTNActionPerformed(evt);
            }
        });
        jPanel2.add(FECHAR_BTN);
        FECHAR_BTN.setBounds(500, 440, 70, 30);

        jLabel1.setText("Calculando seu IMC");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(240, 20, 150, 20);

        peso_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso_txtActionPerformed(evt);
            }
        });
        jPanel2.add(peso_txt);
        peso_txt.setBounds(140, 80, 330, 20);

        alt_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt_txtActionPerformed(evt);
            }
        });
        jPanel2.add(alt_txt);
        alt_txt.setBounds(140, 50, 330, 20);

        jLabel2.setText("ALTURA");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 50, 50, 14);

        jLabel3.setText("PESO");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 90, 50, 14);

        LIMPAR_BTN.setText("LIMPAR");
        LIMPAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPAR_BTNActionPerformed(evt);
            }
        });
        jPanel2.add(LIMPAR_BTN);
        LIMPAR_BTN.setBounds(400, 440, 80, 30);

        jLabel5.setText("Seu IMC é: ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(230, 240, 70, 30);
        jPanel2.add(resp_txt);
        resp_txt.setBounds(290, 250, 260, 14);

        Enviar_BTN.setText("Enviar");
        Enviar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enviar_BTNActionPerformed(evt);
            }
        });
        jPanel2.add(Enviar_BTN);
        Enviar_BTN.setBounds(490, 60, 70, 30);

        img1_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/abaixodopeso.png"))); // NOI18N
        jPanel2.add(img1_img);
        img1_img.setBounds(20, 110, 200, 330);

        img2_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pesoideal.png"))); // NOI18N
        jPanel2.add(img2_img);
        img2_img.setBounds(40, 110, 210, 320);

        img3_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/acimadopeso.png"))); // NOI18N
        jPanel2.add(img3_img);
        img3_img.setBounds(30, 160, 210, 300);

        img4_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/obesidade1.png"))); // NOI18N
        jPanel2.add(img4_img);
        img4_img.setBounds(20, 90, 170, 350);

        img5_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/obesidade2.png"))); // NOI18N
        jPanel2.add(img5_img);
        img5_img.setBounds(20, 100, 250, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(600, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FECHAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FECHAR_BTNActionPerformed
    System.exit(0);   
    }//GEN-LAST:event_FECHAR_BTNActionPerformed

    private void alt_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alt_txtActionPerformed

    private void Enviar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enviar_BTNActionPerformed
    Controller.Calcula_DAO.calculo();
    }//GEN-LAST:event_Enviar_BTNActionPerformed

    private void LIMPAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMPAR_BTNActionPerformed
    Controller.Calcula_DAO.limpar();
    }//GEN-LAST:event_LIMPAR_BTNActionPerformed

    private void peso_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peso_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraIMC_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraIMC_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraIMC_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraIMC_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraIMC_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enviar_BTN;
    private javax.swing.JButton FECHAR_BTN;
    private javax.swing.JButton LIMPAR_BTN;
    public static javax.swing.JTextField alt_txt;
    public static javax.swing.JLabel img1_img;
    public static javax.swing.JLabel img2_img;
    public static javax.swing.JLabel img3_img;
    public static javax.swing.JLabel img4_img;
    public static javax.swing.JLabel img5_img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField peso_txt;
    public static javax.swing.JLabel resp_txt;
    // End of variables declaration//GEN-END:variables
}
